imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"    
    paths:
        "%kernel.root_dir%/Resources/views/admin": admin
        "%kernel.root_dir%/Resources/views/establishment": establishment
    form:
        resources: ['bootstrap_3_horizontal_layout.html.twig']
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User 
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\BaseUser
    profile:
        form:
            type: AppBundle\Controller\Form\ProfileFormType
    registration:
        confirmation:
            enabled:    true
    from_email:
        address:        do_not_respond_register@voyagir.org
        sender_name:    Voy'agir

# OAuth
hwi_oauth:
    connect:
        account_connector: app.provider.oauth
    firewall_name: main
    http_client:
        verify_peer: false
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            google: google_id
            twitter: twitter_id
    resource_owners:
        # Facebook Access
        facebook:
            type:               facebook
            client_id:          1101303959940546
            client_secret:      e9bfd3028e868e23b6e91e92e72eb6bf
            scope:              "email"
            infos_url:          "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email:          email
        google:
            type:           google
            client_id:      504565395085-idsmt0i7ojsbneaj4t3kv88dp8ell30l.apps.googleusercontent.com
            client_secret:  gi_im0-LF_eMcnVANa66-aWR
            scope:          "email profile"

# Vich
vich_uploader:
    db_driver: orm
    mappings:
        establishment_image:
            uri_prefix:         /img/etb
            upload_destination: %kernel.root_dir%/../web/img/etb
            namer:
                service: vich_uploader.namer_property
                options: { property: 'imageNameById'}
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true