# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    0service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    utils.user_security:
        class: AppBundle\Services\UserSecurity
        arguments: ['@security.token_storage', '@security.authorization_checker']
    app.business_service_factory:
        class: AppBundle\Services\Business\BusinessServiceFactory
        arguments: ['@doctrine', '@logger']
    app.etb_voter:
        class: AppBundle\Security\EstablishmentVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    
    app.etb_act_listener:
        class: AppBundle\Services\Listeners\EstablishmentActivityListener
        arguments: ['@logger']
        tags:
            - { name: doctrine.event_subscriber, event: prePersist, connection: default }